version: '3.4'

services:
  todoitemdb:
    container_name: todoitemdb
    environment:
      SA_PASSWORD: "Bob12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
  todoitem.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:TodoItemConnectionString=Server=todoitemdb;Database=TodoItemDb;User Id=sa;Password=Bob12345678"
    depends_on:
      - todoitemdb
    ports:
      - "8001:80"

