concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://gitlab-web:9090"
  token = "FjydCYJFYmcUpMzBv_mP"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["C:\\Program Files\\Git\\var\\run\\docker.sock;C:\\Program Files\\Git\\var\\run\\docker.sock", "/cache"]
    shm_size = 0

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://gitlab-web:9090"
  token = "zzpyNGhVjL-HRJsQoYRR"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["C:\\Program Files\\Git\\var\\run\\docker.sock;C:\\Program Files\\Git\\var\\run\\docker.sock", "/cache"]
    shm_size = 0

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://gitlab-web:9090"
  token = "NyZ-aJxqqUGRsJGFhs7G"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://gitlab-web:9090/"
  token = "wiXK8ypLLzjJb5Z39ACm"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://gitlab-web:9090/"
  token = "jZJZusKfE7wUACi59j6-"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "Dotnet 6 Web.API Runner"
  url = "http://172.19.0.2:9090"
  token = "Wj_eCK92QDP625cnvHRs"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
